### ISSUE TITLE
WorldWind setMilStdLabels is broken

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#10]
Changing the milStdLabel setting in WorldWind results the map being completely obscured by a green layer.

**Comment by jaybarra** [comment]
Fix branch: **bugfix/emp3-web-10-ww-milstdlabels**

### Changes: 
* Single point milStd symbols should now correctly display the labels correctly
* Multi-point symbols should not change by changing the maps label style.
* The map should now behave normally when changing the map label style

**Comment by jamesbeecroft** [comment]
Jay, labeling looks good. I'm going through graphics to make a list of ones that are not displaying correctly. I will submit that as a separate issue.
