### ISSUE TITLE
Implement map smart move in Cesium.

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#101]
Implement map smart move in Cesium.

**Comment by alberto-acevedo** [comment]
Test case:

Use the API tester and enable the smart motion lock mode. Right click the borders of the map and keep the mouse down. The test is a success if the map moves as follows:

right side - moves to the right
left side - move left
top side - move top
bottom side - move bottom
top Left corner - move top left
top right corner - move top right 
bottom Left corner - move bottom left
bottom right corner - move bottom right

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
