### ISSUE TITLE
Primitive circles (PBS_CIRCLES) loose accuracy with large radius like for example 1,500,000

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#112]
The accuracy deteriorates  the bigger the radius. I tested isolate that is a symbol having 2 points and the accuracy is excellent with big radius. Can the renderer apply same calculation that is done to isolate for parameterized symbols?

![image](https://cloud.githubusercontent.com/assets/2699867/23412141/ada8d0f0-fda2-11e6-9db2-758571c4d58b.png)

**Comment by mdeutch3** [comment]
A fix was checked into mil-sym-js. The large ellipses are not perfect if the semi-major axis = semi-minor axis, maybe you could use PBS_CIRCLE for those.

**Comment by alberto-acevedo** [comment]
Latest renderer built from master fixed the issue., The fix did not make it into the 2,1.0 release. I will merge into the development branch.
