### ISSUE TITLE
Screen Graphic is not rendering correctly based on coordinates

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#119]
The Screen (Tactical Graphics/Task) graphic is not rendering the coordinates correctly based on the input from the create mil-standard test script. The correct rendering is occurring in Cesium. Screen captures and test script provided for reference. 
![Uploading CesiumScreenGraphic.png…]()
![Uploading WorldWindScreenGraphic.png…]()
[Uploading script_create_overlay_milstdfeatures.zip…]()

**Comment by jamesbeecroft** [comment]
Original Links for Graphics Screen Capture and Scripts are inoperative. 
![worldwindscreengraphic](https://cloud.githubusercontent.com/assets/25467634/23664737/64d09c1e-0324-11e7-858c-229996517bdf.png)
![cesiumscreengraphic](https://cloud.githubusercontent.com/assets/25467634/23664741/684fcd1a-0324-11e7-8457-8ce18f20305c.png)
[script_create_overlay_milstdfeatures.zip](https://github.com/missioncommand/emp3-web/files/824949/script_create_overlay_milstdfeatures.zip)

**Comment by alberto-acevedo** [comment]
Not able to replicate this issue. The screen looks the same in WW and Cesium.

**Comment by alberto-acevedo** [comment]
Test case:
Use the dev branch.
Use WW
Use the attached script.
The test is a success if the screen looks the same in WW and Cesium. The screen will render near California.

**Comment by mubinakhan** [comment]
Reintegrate . Fixed

**Comment by alberto-acevedo** [comment]
Already fixed in the dev branch. Closing this issue.
