### ISSUE TITLE
Implement the map motion lock for no pan, no zoom, no zoom no pan in Cesium

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#121]
Implement the map motion lock for no pan, no zoom, no zoom no pan in Cesium.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 121

Use the api tester and test map motion lock for no pan, no zoom, no zoom no pan. The test is a success if the lock mode behaves as expected.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
