### ISSUE TITLE
Ellipse primitive is rotating when the sky is visible

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#122]
This issue was just fixed by Mike Deutch. I'm just adding the issue to keep a record of the fix.

**Comment by alberto-acevedo** [comment]
test case:

PLot an ellipse with the following values:
semi major = 2000000
semi minor = 500000

Then zoom out until the sky is visible. The test is a success if the ellipse does not rotate.

**Comment by alberto-acevedo** [comment]
The is a minor issue with the ellipse not looking symmetrical with big semi major and small semi minor. I would consider this another issue not related to this issue of ellipse rotating.

**Comment by mdeutch3** [comment]
A fix for the issue with symmetry was checked into mil-sym-js repository.

**Comment by mdeutch3** [comment]
The Cesium source for ellipses has been implemented in the renderer, I'm not seeing a problem with large semi-major and semi-minor axes.

**Comment by alberto-acevedo** [comment]
Tested by Jimmy. No issues  found with latest rendrer. Clsoing this issue.
