### ISSUE TITLE
Ellipse in Cesium is not symmetrical with large semi major values.

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#125]
Small ellipses look symmetrical, but the larger the semi major the less symmetrical the resulting graphic.

**Comment by mdeutch3** [comment]
A fix was checked into mil-sym-js. It improves the symmetry of large ellipses.

**Comment by alberto-acevedo** [comment]
The ellipse is not symmetrical and now the ellipse moves or  elongates  when clipped. Using a semi-major of 5000000 and semi minor of 300000.

**Comment by mdeutch3** [comment]
Is it supposed to be symmetrical? I can try increasing the number of points, it may help some.
![sandcastle ellipse](https://cloud.githubusercontent.com/assets/5973557/23559697/d80de5b4-0005-11e7-84d2-3342345c218a.png)

**Comment by mdeutch3** [comment]
A revision for PBS_ELLIPSE was checked into mil-sym-js today. The Cesium code for ellipses has been implemented. We do have some flexibility on the granularity.

**Comment by alberto-acevedo** [comment]
I  tried the latest renderer from master. It fails to render with the following error:

{"type":"MultiPointHandler","RenderSymbol2D":"There was an error creating the MilStdSymbol PBS_ELLIPSE----: - undefined - "}

**Comment by mdeutch3** [comment]
That’s odd, I ran with dev branch this morning and it was Ok. I’ll take a look.

 

Michael Deutch

Shonborn-Becker Systems Inc. (SBSI)

415-937-5368

Email:  <mailto:mdeutch3@comcast.net> mdeutch3@comcast.net

 

This electronic message contains information from Shonborn Becker
Systems, Inc., which may be company sensitive, proprietary, privileged
or otherwise protected from disclosure

**Comment by mdeutch3** [comment]
Are you using the default savm-bc.js that is under validation\vendor\mil-sym which has 7901016 bytes? That one is not latest, it doesn't have the Cesium ellipse code in it, although it should still recognize PBS_ELLIPSE.

**Comment by mdeutch3** [comment]
The error is occurring in EmpCesium and not in the renderer.

**Comment by mdeutch3** [comment]
![bad am data](https://cloud.githubusercontent.com/assets/5973557/23776155/706a8706-04fa-11e7-985c-61da91444d0b.png)

Sometimes bad AM data is coming into the web workers. AM[0]=0, AM[1]=5000 which won't generate an ellipse. That's causing the renderer to throw an error and subsequently EmpCesium gets nothing back from the worker and is generating the error you reported.

**Comment by alberto-acevedo** [comment]
I tested again and the API tester is sending the correct AM values. AM = [300000, 5000000, 0]. Same error. i will step unto the RenderSymbol2D and see if there is something wrong with the rest of the values. Circle is working fine.

**Comment by alberto-acevedo** [comment]
I found the issue. The function EllipseGeometry(options)  throws an error is the semiMayor < semiMinor
Line 167703.

**Comment by mdeutch3** [comment]
The previous version did not use Cesium open source and was using pixels. It did not throw an error if semi-major < semi-minor. But semi-major has been AM[0] and semi-minor is AM[1].

**Comment by alberto-acevedo** [comment]
I had AM[0] as the semi-minor and I AM[1] as the semi-major. i just switched the values.. Now the ellipse shows that the values are swapped. Take a look to the snapshot using the API tester:

![image](https://cloud.githubusercontent.com/assets/2699867/23802896/cb6d6bf4-0582-11e7-9b32-51a581fd020c.png)

**Comment by mdeutch3** [comment]
If AN[0]=0 then that is how it is supposed to appear.

**Comment by alberto-acevedo** [comment]
Yes AN[0]=0.  I tested same values in sandcastle and the rendering looks different. Take a look to snapshot. In SandCastle the semi-major is applied horizontally when the rotation is zero.


![image](https://cloud.githubusercontent.com/assets/2699867/23803773/91597540-0585-11e7-884d-07c5228613a1.png)

**Comment by mdeutch3** [comment]
@michael-spinelli We've always used 0 as true north and clockwise rotation for Mil-Std-2525 graphics and basic shapes. Please advise.

**Comment by alberto-acevedo** [comment]
Test case:

Use the development branch.

Plot an ellipse: AM = [700000, 300000, 0], AN=[0]
The test is a success if the ellipse renders, is symmetrical., and the semi-major is aligned horizontally with the x axis..

Note: at very large semi-major, semi-minor, the ellipse looks like a  polygon. This is a limitation in Cesium and not a  bug in the SEC tenderer.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Already merged into the dev branch closing this issue.
