### ISSUE TITLE
Example in dev-guide "Update existing MIL-STD" stops working after a few updates in Cesium

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#126]
In the example in the dev guide,  "Update existing MIL-STD", the point is supposed to move around the globe and update every 50ms.    However after the point approaches the edge of the globe it stops, never to update again, unless the map is moved or zoomed in on that point.  The point should actually update continuously and disappear if it moves out of the map area.    Furthermore, it should not stop updating.  Fix Cesium map so that this works.

**Comment by alberto-acevedo** [comment]
Replaced the getExtet() with a built  in sdk function tyat uses an occluder to detrmone if a point is visible or not. The occluder did not take into consideration the case of billboards too close to the horizon. When the billboard is too close to the horizon and the position is occluded, the billboarded behavior of the graphic can keep it visible. The solution was to calculate the distance and bearing from the center of view to the billboard (distanceCenterTobillboard)  and then calculate a position that is 10% of the  distanceCenterTobillboard , with same bearing - 180 away from the billboard. If the new position is not occluded than Cesium renders it. Works very well.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 126.

Run the example in the dev guide, "Update existing MIL-STD", The test is a success if the point move around the globe and update every 50ms. If the point get stuck at the horizon the the test fails.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
