### ISSUE TITLE
Example in dev-guide, "Create a MIL-STD-2525 multipoint", does not show all symbols in Cesium .

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#127]
There are 2 examples, "Create a MIL-STD-2525 multipoint" and "set the visibility of an overlay", which 3 symbols are added to the map.   In both cases, one of the symbols does not show.   In both cases all 3 features are added to the map at the same time, then the map zooms to the overlay prior to the features being shown (as the map is returned success of the feature add PRIOR to the feature being added by the engine.)  The zoom works and is in right area, however it looks as though the renderer is clipping the images out of the picture because if you zoom slighltly out the renderer displays the missing graphics.  Fix this.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch #126.

 Run 2 examples in dev guide:, "Create a MIL-STD-2525 multipoint" and "set the visibility of an overlay"

The test is a success if all 3 features show on the map.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
