### ISSUE TITLE
Create point editor for Worldwind

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#13]
Allow editFeature method to work for emp3.api.Point class and single point emp3.api.MilStdSymbol in Worldwind.

To do this we are beginning to remove editing capability out of the engines themselves and put editor capability into the core map.   This will unify all map engines to edit the same way.

**Comment by sjpinizzotto** [comment]
@jamesbeecroft Jimmy, you'll need to test all point graphics, Point class and MilStd point items.  Need to make sure callbacks are returning correct data, (start edit, edit update, edit cancel, edit complete).  Need to validate that all the other types of editing are good. (lines, polygon, milstd multipoint.)

**Comment by jamesbeecroft** [comment]
reintegrate
