### ISSUE TITLE
Implement rendering optimization for WorldWind

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#131]
MilStdSymbol objects should be redrawn as points at a specific altitude to improve performance

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 131

- sset icon label option to all labels
- set mid and high optimization altitude ranges.
- Plot mil standard single points.
-  Zoom in and out. The test is a success if the optimization is present. Low range the single point shows the symbol with modifiers if any; mid range, the symbol shows but no modifiers; high range, the symbol is replaced by a dot with the color representing the affiliation.
-  Test for updates of affiliation at high altitude range. The dot must change color based on the updated affiliation.
- Test for selection.

**Comment by jamesbeecroft** [comment]
Everything good, but selection. Selection is not highlighting the single point, but enlarges the graphic to show the icon itself instead of the dot at higher altitude.
