### ISSUE TITLE
Default Line Width For Graphics in WorldWind are Too Thick, Graphics Look Block-like

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#135]
When rendering Mil-Std graphics in WorldWind, the graphics line weight is too thick, making the graphics look block-like. 
![rendererworldwind](https://cloud.githubusercontent.com/assets/25467634/23673749/713358c6-0341-11e7-914e-cad6a7d1e125.png)

**Comment by jamesbeecroft** [comment]
Also causes primitives at distant scales to render as different shapes until the user zooms in. Square and Rectangles appear as a cross on the map. 
![renderingsquarerectangle_worldwind](https://cloud.githubusercontent.com/assets/25467634/23710038/5dc827b4-03e9-11e7-89b5-821f5a5b43f7.png)

**Comment by michael-spinelli** [comment]
if it's a line width issue, you could set armyc2.c2sd.renderer.utilities.MilStdAttributes.LineWidth in the modifiers object sent to the renderer.

**Comment by jaybarra** [comment]
Branch _feature/emp3-web#135-ww-line-thickness_

**Comment by jamesbeecroft** [comment]
Reintegrate
