### ISSUE TITLE
Point of Departure is changing locations after user zooms or pans after edit script is applied

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#138]
After a user creates and edits the mil-std graphics via the test scripts, point of departure changes geographic location when the user zooms or pans the map. 

[script_create_overlay_milstdfeatures.zip](https://github.com/missioncommand/emp3-web/files/825718/script_create_overlay_milstdfeatures.zip)
[script_edit_overlay_milstdfeatures.zip](https://github.com/missioncommand/emp3-web/files/825719/script_edit_overlay_milstdfeatures.zip)
![pdworldwind_originallocation](https://cloud.githubusercontent.com/assets/25467634/23676273/29717cb2-034a-11e7-8107-e711f0d8ed39.png)
![pdworldwind__editlocation](https://cloud.githubusercontent.com/assets/25467634/23676274/2b67a456-034a-11e7-91ba-74bae4889eac.png)
![pdworldwind__locationafterinteraction](https://cloud.githubusercontent.com/assets/25467634/23676276/2ce69a80-034a-11e7-8929-ecefcdf56270.png)

**Comment by jaybarra** [comment]
Update was not being applied to the stored feature. 
test branch *bugfix/emp3-web#138-ww-feature-update-position*

**Comment by jamesbeecroft** [comment]
Reintegrate
