### ISSUE TITLE
Removal of Mil-Std Graphics in WorldWind via Script has graphics reappear on user interaction

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#139]
When removing mil-std graphics using the test script, the graphics are initially removed from WorldWind, but reappear if the user pans or zooms on the map. The map validation tool emp visualizer shows that all graphics have been successfully removed from the map. 
[script_create_overlay_milstdfeatures.zip](https://github.com/missioncommand/emp3-web/files/825736/script_create_overlay_milstdfeatures.zip)
[script_remove_overlay_milstdfeature.zip](https://github.com/missioncommand/emp3-web/files/825737/script_remove_overlay_milstdfeature.zip)

**Comment by jaybarra** [comment]
Most likely causing #138 , will investigate

**Comment by alberto-acevedo** [comment]
Tested by removing all renderables from the renderable layer and the graphics removed appear again when zooming in and out. This only happens with lines and polygon graphics. points (icons) and labels are correctly removed with no issues. This appear to be a WW bug that is somehow caching the graphics. Continue investigating
