### ISSUE TITLE
Stroke Color on Primitives is not being applied in WorldWind

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#141]

**Comment by jamesbeecroft** [comment]
[script_edit_overlay_simpleshape.zip](https://github.com/missioncommand/emp3-web/files/828010/script_edit_overlay_simpleshape.zip)
[script_remove_overlay_simpleshapes.zip](https://github.com/missioncommand/emp3-web/files/828011/script_remove_overlay_simpleshapes.zip)
[script_create_overlay_simpleshapes.zip](https://github.com/missioncommand/emp3-web/files/828009/script_create_overlay_simpleshapes.zip)
When applying color values to the Stroke Field, the values are not being applied in WorldWind. All stroke colors for primitives are being rendered in black.

**Comment by jaybarra** [comment]
testBranch _bugfix/emp3-web#141-ww-stroke-color_

**Comment by jamesbeecroft** [comment]
Reintegrate
