### ISSUE TITLE
Apply should not be used as a function name

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#162]
This affects messageHandler and all of the container classes.

`apply` is a reserved word in JavaScript. The native apply method is being overwritten by our use of the function. This does not seem to be causing problems currently but this should be changed if possible.

**Comment by sjpinizzotto** [comment]
I propose we change it to "update"

**Comment by erikamarie** [comment]
Ready for testing. Use overlay and feature updates from validation tool. Ensure updates worked with toaster and in console that warning is displayed "XX.apply is deprecated. Apply is reserved word in javascript. Use XX.update."

**Comment by jamesbeecroft** [comment]
Reintegrate
