### ISSUE TITLE
WorldWind is not emitting the correct camera events

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#18]
Map motion events are returned as map stopped,
No map stopped event is being fired when a goto animation completes

**Comment by jaybarra** [comment]
fixbranch **feature/emp3-web-#18-ww-camera-events**

### new behaviors
* WW will emit camera events when
** dragging
*** CAMERA_IN_MOTION events while dragging
*** CAMERA_MOTION_STOPPED events when the mouse button is released
** map.setLookAt with animation should emit a start and stop events appropriately
** map.setCamera with animation should emit a start and stop events appropriately

**Comment by jamesbeecroft** [comment]
REINTEGRATE
