### ISSUE TITLE
WorldWind is ignoring initial bounds as part of the constructor

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#185]
The initial bounds are not being used in the WorldWind constructor

**Comment by jaybarra** [comment]
Test branch 
_bugfix/emp3-web#185-ww-initial-bounds_

Use the createMapTest to verify, setting bounds should work, also contrast should be passed in correctly
_worldWindMapEngine_ is the engine key

**Comment by jamesbeecroft** [comment]
Reintegrate
