### ISSUE TITLE
Editing in Leaflet is broken

### ISSUE THREAD

**Issue by nclark25** [missioncommand/emp3-web#193]
Although the editing handles now show up, dragging of these handles only selects the editing handle graphic.

**Comment by nclark25** [comment]
Dragging the editing points now works but there is a problem with the smart motion lock movement that is causing the map to pan when moving the mouse anywhere.

**Comment by nclark25** [comment]
Completed the fix regarding smart motion lock movement. Finished testing various graphics to make sure that editing was working for the currently supported editors.

**Comment by nclark25** [comment]
Testing Procedure:

Run full suite of edit tests on Leaflet map.

**Comment by jamesbeecroft** [comment]
Primitive Points is jumping around a bit, on the edit move, Mil-Std units are not moving on editing. Ellipse and Square have not been merged into development yet.

**Comment by nclark25** [comment]
Simple point and mil-std point editing should no be fixed.

**Comment by jamesbeecroft** [comment]
Reintegrate. The jumping movement for primitive points and mil-std points no longer occurs.
