### ISSUE TITLE
Firefox wheel delta is not being detected correctly

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#194]
Chrome uses wheelDeltaY, Firefox uses deltaY

**Comment by jamesbeecroft** [comment]
When trying to build the wars, the process aborts and does not create them. emp3ToValidation

**Comment by jamesbeecroft** [comment]
Moving to Backlog, Jay Barra confirmed this is a WorldWind issue, and needs to be resolved on their end.
