### ISSUE TITLE
Add map rendering optimization to Leaflet

### ISSUE THREAD

**Issue by nclark25** [missioncommand/emp3-web#2]
Add ability to handle rendering optimization for Leaflet.

Leaflet should accept object in manifest engine constructor call that turns on/off rendering optimization and sets the default value.

Leaflet shall be able to change those settings when config method is called modifying those settings.
When map altitude is at the approximate farDistanceThreshold, draw single point MIL-STD symbols as dots.

When map altitude is below the farDistanceThreshold, single point MIL STD symbols show icons without labels.

When map altitude is below the approximate midDistanceThreshold, single point MIL STD symbols show icons labels according to the MILSTD labels setting.

**Comment by jamesbeecroft** [comment]
Reintegrate
