### ISSUE TITLE
In Cesium engine, Mil-Std-2525 3D Multipoint labels are rendering at 0 altitude

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#20]
The labels must take the highest altitude from the modifiers so the labels are alwys on top of the graphics.

**Comment by alberto-acevedo** [comment]
Test case:

Plot a mil standard air corridor. Set name "label on top"
set altitudeDepth to: 50000,100000
set distance to: 20000

The test is a success if the mil standard renders in 3D with the label on top of the graphic.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Fixed already in dev branch. No modifications done to this #20 branch. closing this issue.
