### ISSUE TITLE
Editing in WorldWind is inconsistent

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#200]
When editing graphics in WorldWind, the user may have to left-click and drag the point on the graphic 2 to 3 times before the edit occurs.

**Comment by jaybarra** [comment]
test branch _bugfix/emp3-web#200-ww-editing-fix_
Grabbing edit points should be consistent now

**Comment by jamesbeecroft** [comment]
Reintegrate
