### ISSUE TITLE
Icon not changing size when user applies size change

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#203]
When changing the Icon Size in World Wind, the icons do not change size when the user chooses a value.

**Comment by alberto-acevedo** [comment]
Test case:
Use branch 2.6..0 release
Use the API tester.   
Plot a mil standard icon.
Set Map/ IconSize.
The test is a success if the icon change its size.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the release 2.6.0 branch. Closing this issue.
