### ISSUE TITLE
VisibilityEvents for emp3.api.KML & emp3.api.GeoJSON do not return the correct feature object

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#21]
KML & GeoJSON feature visibility events aren't creating correct feature types during event generation

**Comment by alberto-acevedo** [comment]
Not able to replicate issue of visibility event with wrong feature types. For kml the featureType  is kml, and for geojson the type is geojson.

**Comment by alberto-acevedo** [comment]
test case plot the following geojson:

[test feature collection.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca9ed86201671a0080a5da/125516c66e82c728ace21e0d46fc918937c285ac8efdaa51a11df39b254a22703d0dac2532c9a138ad4d71040c1b5ca6535d5717f5ffdb2ff4b039238b580cedd1650a20c36b10adba9003ad43eb7edf10d8eff6df0ed2e22f26e6818e4a3e1e031e8bf75b32a0984eda15.txt)

Subscribe to the visibility event. 
The test is a success if the event generated has the featureType as geojson.


test case plot the following kml:


[eric.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca9ed86201671a0080a5da/125516c66e82c728ace21e0d46ed869320c0cfeb9ffbb049a15ee4d67304722b2a5df5292487b57dbc132f565f5f46f9155d0945fdfb9b37b4f46d2ede0356b49b381d66cc2f13aab2831abf01bc26884e84b6ba8c49d2a5.txt)


Subscribe to the visibility event. 
The test is a success if the event generated has the featureType as kml.

**Comment by mubinakhan** [comment]
[Uploading kml.PNG...]

**Comment by mubinakhan** [comment]
reintegrate

**Comment by alberto-acevedo** [comment]
Closing this issue . Nothing to merge.
