### ISSUE TITLE
Leaflet border panning during Smart Motion Lock is not implemented correctly

### ISSUE THREAD

**Issue by nclark25** [missioncommand/emp3-web#211]
Border panning during smart motion lock only occurs when the mouse is down AND a mouse move generates. Mouse down in border area should cause map to move without a mouse move action.

**Comment by nclark25** [comment]
Testing Procedure:

- Plot various graphics.
- Edit each graphic and while editing move the point to the side of the screen to initiate auto panning in any direction. Make sure that the editing point follows the panning.

**Comment by jamesbeecroft** [comment]
Reintegrate
