### ISSUE TITLE
Use batch capability of SEC worker when redrawing multipoints.

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#212]
Send batch of features to the worker to improve performance.

**Comment by alberto-acevedo** [comment]
Test case:

use branch feature/#212

Use the multipoint performance tester and plot 200 multipoints. Zoom in/out. The test is a success if the fetaures render on the map, and also the features redraw when zooming or panning. You should see a considerable improvement in performance.

**Comment by alberto-acevedo** [comment]
Jimmy - test again.  This time test with 50 so you can test the batching of redraws. The map is throwing hundreds of  fail to load tile errors and that is causing a performance issue in WW. when panning or zooming. The issue  with the tiles is going to make it hard to test for performance  when using the worker.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev  branch.
