### ISSUE TITLE
Editing does not work on slow computer

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#214]
Edit a line or polygon, quickly "flick" the points to a new spot.  The graphic editing will get all out of order, and the line will be incorrect. 

Also, a mouse down and up over a point will allow  you to drag the point while the mouse is up.   This should be fixed as well.

Susupect the mouse up event is not raising.  investigate.

**Comment by sjpinizzotto** [comment]
Use the following script to test.  This is the copy of the example in the dev guide.  Try whipping the points around now.  Points should never go out of order.    Test polygons, points, and other draw/edit types.   

NOTE: this branch is based on the draw branch, so it will have the same issues the draw branch has.


var overlay1 = new emp3.api.Overlay({
  name: "overlay1",
  id: "w834mne-sdg5467-sdf-we45"
});

var path = new emp3.api.Path({
  name: "myPath1"
});

// After we know an overlay has been added, we can draw the symbol.
// You don't need an overlay to draw, but when the draw is complete,
// we want to add the returned feature to the map.
function processAdd() {
  var count = 0;

  // This is just an example.  Customize drawing and editing however you like!
  alert("Click on the map to begin drawing.  Click 3 times to end drawing and go into edit mode.  Right-click to exit edit mode.");

  // This just puts the map in draw mode, so the map begins
  // animating the draw.  It does not actually add data to the map.
  map0.drawFeature({
    feature: path,
    onDrawUpdate: function() {
      // once we hit three, end the draw.  (this is not necessarily what you
      // do--just a way to end the draw)
      count++;
      if (count >= 3) {
        map0.completeDraw();
      }
    },
    onDrawComplete: function(args) {
	  console.log("draw complete");
      // this is what actually adds the feature to the map.
      overlay1.addFeature({
        feature: args.feature,
        onSuccess: function() {
		  console.log("feature add complete");
		  // Right click to end the edit
		  function myListener(cbArgs) {            
	        if (cbArgs.event === emp3.api.enums.UserInteractionEventEnum.CLICKED && 
		      cbArgs.button === emp3.api.enums.UserInteractionMouseButtonEventEnum.RIGHT) {			  
			    map0.completeEdit();
	        }		         
          }

		  // Add a map event listener so we know when to finish the edit.  In this case
		  // we will finish the edit on a right click.
          map0.addEventListener({
            eventType: emp3.api.enums.EventType.MAP_INTERACTION,
            callback: myListener
          });
		 		  
          map0.editFeature({
            feature: args.feature
          });
        }
      });
    }.bind(this)
  });
}


function processError(error) {
  alert(JSON.stringify(error));
}

// add an overlay to the map.
map0.addOverlay({
  overlay: overlay1,
  onSuccess: processAdd,
  onError: processError
});

**Comment by jamesbeecroft** [comment]
Reintegrate
