### ISSUE TITLE
Improve WorldWind event handling performance

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#215]
A general improvement task to optimize the event handling.
## Goals
* reduce call volumes without affecting WorldWind
* reduce overall complexity
* eliminate mouseevent/pointerevent duplicate handling (Chrome)

**Comment by jaybarra** [comment]
For testing purposes verify any kinds of noticeable improvements in performance

**Comment by jamesbeecroft** [comment]
Reintegrate
