### ISSUE TITLE
Worldwind map fails to load when performing a map swap

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#22]
When performing a map swap, swapping to worldwind fails to load the worldwind base map layer. Only a gray screen appears. A green toastr message appears in the upper right of the browser indicating a successful swap operation. The failure occurs in emp-2834 and development branches. Cesium and Leaflet have no issues performing map swap.

**Comment by jamesbeecroft** [comment]
Reintegrate
