### ISSUE TITLE
Cesium movement momentum occurs when map is locked

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#221]
Create a line and enter edit mode.   In this mode the map locks on mouse down and over a feature.

Click on a feature point and try to "whip" the map.  If done fast enough, the map will move despite it being locked.  If you do it slow, the map behaves as required.  

Fix Cesium so that when the map is locked, it will cancel or prevent any movement.

**Comment by alberto-acevedo** [comment]
I had exactly the same issue with the Cesium editors. The solution is to delay the unlocking of the map with a timeout.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch #212

Create a line and enter edit mode. In this mode the map locks on mouse down and over a feature. Click on a feature point and try to "whip" the map. The test is a success if the map does not move.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
