### ISSUE TITLE
Allow MIL-STD-2525 multipoints with finite number of points to draw in Worldwind

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#225]
Create a generic MIL-STD-2525 editor for any graphic with a finite number of points

**Comment by sjpinizzotto** [comment]
To test, test any MIL-STD-2525 multipoint except axis of advance types, or range fans.  Test graphics with max points of 2 (isolate), 3 (bypass, ambush), 4 (relief in place, assault crossing area), 2 points lines (linear target) arrows (direction of attack) and two point arrows (fix)

**Comment by jamesbeecroft** [comment]
Reintegrate
