### ISSUE TITLE
Replace default images with android images in map core

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#227]
Replace default imagery in editors with the point images from android.  The points should be made an appropriate size, stored as base64 images, and used.  

Also replace our default point image with the android default point image.

The android default images can be found here:

https://github.com/missioncommand/emp3-android/tree/development/sdk/sdk-core/aar/src/main/res/drawable-ldpi

**Comment by jamesbeecroft** [comment]
Reintegrate
