### ISSUE TITLE
When drawing a default point, the image offset is incorrect

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#228]
When drawing a point with no iconURL, the default point image is placed at the wrong spot.  

In Cesium the image is off to the left of where you click.  

If each Map Engine places the image in different relative locations when an offset is given, fix engines so they interpret the offset correctly.  We made need to discuss the correct offset position for icons and where the reference should be.

**Comment by alberto-acevedo** [comment]
Fixed offset location for all engines. Each engine has a different way to set the offset. 

Cesium - Only take pixels, together with setting the vertical origin to bottom. Using default icon offset values that are supposed to be fractions.

WorldWind - The x offset has to be a fraction, and the y offset has to be in pixels. Using default icon offset values that are supposed to be fractions.

Leaflet - I had to use pixels and set the values to x = 12.5, y = -41. Tried using default icon offset as fraction and it failed.  I check if the iconURL contains the default icon base URL. If found then I make the swap of values from fraction to pixels.

The default icon in the emp.ui is different from the icon in the emp.untilities. Decided to replace the icon in the ui with the icon from the utilities that looks sharper.

This is a fix but it is not a clean solution. I will revisit this fix later on. There are possibilities of bugs in the map sdks that could explain the different ways of handling offset values.

Test case:

use branch 228.
use all maps.
plot points, draw points, edit points. 
The test is a success if the default icon tip is exactly at the specified location.

**Comment by mubinakhan** [comment]
![7-14.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46bfd9cb77c0cfeb9ffbb049a15ee4d67304722b2a5df5292487b57dbc132f565f5f46f9155d0945fdfb9b37b4f46d2ede0356b49b381d66cc2f12adb2831abf01ba268c4982b7b58f4ad2a5.PNG)
![7-14-17.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46bfd9cb77cfd2fecda5fd53b652fa912a5265296b51fb2829d3e17cbd142e025e5b49ac41500a10f9af882aa4a42062c80d55b98e30063e937f03a6aa811eb500bf208b4f83b1ba8d45c0ea3837aa.PNG)
![7-14cesium.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46bfd9cb778186ba86fcb201e81fe086264c22703d46f96925dde071e9402f03595a1dad455f5f44f4acdd2ef0b73d72984019af80330b2b9b645bf9fa9015ad02bb2a8a4a85b6bc8c4bc6e1382de1839d02.PNG)
![cesiumdra.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46eb91892a978ead9de8fd0fe64de29b234324676b5ee17e2886ba7ebd1679575a0c4fa846585f4ca9ad8c7da7b73e62964e49bc8f3900299f7744eeaa880dbc00b0218e4f85b6ba8d4bc1e1342cee99c2.PNG)
![cesiumedit.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46eb91892a978eac8be0ab01e81fe086264c22703d46f96925dde071e9402f03595a1dad455f5f44f4acdd2ef0b73d72984019af80330b2b9b645bf9fa9015ad02bb2a8a4a85b6bc8c4bc7eb3e26e0829d02.PNG)
![leaf.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46e4919b25c0cfeb9ffbb049a15ee4d67304722b2a5df5292487b57dbc132f565f5f46f9155d0945fdfb9b37b4f46d2ede0356b49b381d66cc2f12adb2831abf01ba268c4886bfbf894cd2a5.PNG)
![leafletedit.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46e4919b258e86bd8aedb657e611b2843b492d762a10e17132d0bb2be61479550d594bff405c5844fcf1dc7fa3e03d71884e17ff933c0120996048e6edc00db513b826814e80b6bc8a4ac7e03c23e28b8f5d73.PNG)

**Comment by mubinakhan** [comment]
please verify

**Comment by mubinakhan** [comment]
![7-17.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46bfd9cb74c0cfeb9ffbb049a15ee4d67304722b2a5df5292487b57dbc132f565f5f46f9155d0945fdfb9b37b4f46d2ede0356b49b381d66cc2f12adb2831abf01b9228e4e8db0b98b4ed2a5.PNG)

**Comment by alberto-acevedo** [comment]
Passed or failed  the test? I only see a snapshot with no comments. What engine is the snapshot from? The default icon is on target as it is supposed to be. What about the rest of the engines?

**Comment by mubinakhan** [comment]
reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
