### ISSUE TITLE
WorldWind movement occurs when map is locked

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#229]
Create a line and enter edit mode. In this mode the map locks on mouse down and over a feature.

Click on a feature point and try to "whip" the map. If done fast enough, the map will move despite it being locked. If you do it slow, the map behaves as required.

**Comment by jamesbeecroft** [comment]
Found in the fix for Issue 221.

**Comment by jaybarra** [comment]
Still a small issue with the mouse exiting the canvas while editing
Being tracked in NASAWorldWind/WebWorldWind#107

**Comment by jaybarra** [comment]
For testing if the cursor leaves the map area while in smartMotion the dragging will still happen
* Rapid motion within the map should not cause the map to start dragging
* SmartMotion edting should have the control point move with the map 
  * the icon will not show up consistently yet but a white pixel will track the location

**Comment by alberto-acevedo** [comment]
Tested and the issue is still there.

**Comment by alberto-acevedo** [comment]
Fixed issue by calling preventDefault for all event mouse moves . Some browser duplicate move events and the duplicated one was the one causing the issue. fixed and merged in Dev branch.
