### ISSUE TITLE
smart move the map when mouse cursor near borders of map.

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#230]

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 230:

Use Cesium.

Plot a polygon. edit polygon by dragging control point to border of map where the smart map move is activated. The test is a success if the control point stays with the mouse cursor while the map is smart moving. The test is also a success if smart map move ends when positioning the mouse cursor away from  the map area.

I think the editing sometimes brake but I don't think is the engine's fault. The editors in the core needs to get more robust handling the recovery of map motion modes. Sometimes cancelling an edit does not cancel the edit and the smart map mode continues.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
