### ISSUE TITLE
Cesium Performance is Slow during draw or edit complete

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#239]
When editing primitive and mil-std graphics, Cesium can take up to 15-20 seconds to render the graphic on the map, once the user completes the draw or edit complete. Found while testing Issue 189. Issue seems to be specific to Mozilla Firefox ESR 52.0.2 (32-bit)

**Comment by alberto-acevedo** [comment]
Use branch 234 and the Cesium map.

Edit a  primitive and mil-std graphics. The test is a success if the editor are responsive.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
