### ISSUE TITLE
WMTS capability

### ISSUE THREAD

**Issue by nclark25** [missioncommand/emp3-web#240]
WMTS capability needs to be implemented in Leaflet. There are plugins available and these should be leveraged if possible. Licensing must be checked for whichever plugin is used.

**Comment by alberto-acevedo** [comment]
Tested plugin that Nick used in branch #240, Using the plugin the same way as the WMS plugin is not working. I ended up copying properties and functions from the wrapper EMP wmts type:ibrary class into the plugin class, and then passing the plugin class to the parentOverlay as a children layer. The merging of the classes let me to successfully render the WMTS tiles on Leaflet. I will look for the availavility of more plugins that could work better than the one I;m using. Testing is next.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch #240
Use Leaflet.
Use api tester
Use tileMatrixSet = GoogleMapsCompatible.
Select the WMTS layer.
The test is a success if the WMTS data renders on the map.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
