### ISSUE TITLE
Cesium Zoom in Relocates user to Southern Pacific Ocean

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#241]
When a user zooms in on a map, or feature, once the scale bar reaches 30km - 50 km, Cesium will change the map view to be in the southern Pacific ocean. This has been duplicated on Jimmy's, Steve's, and Jay's machines. Found after browser was updated to Mozilla Firefox ESR 52.0.2 (32-bit)

**Comment by alberto-acevedo** [comment]
Test case
 use branch 234 & Cesium map.

The only way to test this issue and other issues in Cesium is by testing in the lab.  Deploy the wars in a computer (DELL) not having the graphic card driver issue. You can test in Firefox 52.0.2.

Zooms in on a map, or feature, to a scale of 30km - 50 km. The test is a success if the map does not teleport to the pacific Ocean.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
