### ISSUE TITLE
Cesium Zoom in causes severe response slowdown of Cesium

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#243]
When a user is zooming in quickly (mouse wheel) the map will seem to lock up in a single view.  After a few minutes, the coordinate tool will start to change. This seems to indicate that the cesium engine may be backed up with processing the requests. Found after installation of Mozilla Firefox ESR 52.0.2 (32-bit)

**Comment by alberto-acevedo** [comment]
Beta graphic driver location for radeon graphic card:

http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows+7+-+64

**Comment by alberto-acevedo** [comment]
Use branch 234 and the Cesium map.

Zoom in quickly (mouse wheel). The test is a success if the map will not lock up in a single view.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
