### ISSUE TITLE
Primitive and Mil-Std Point icons are not displaying correctly

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#244]
When zoomed out, single point graphics are to be displayed as a blue dot (small circle). When zooming in in Cesium, the blue dot changes to a blue pixel. The dot should be consistent until the icon displays. Found after browser was updated to Firefox ESR 52.0.2 (32-bit)

**Comment by alberto-acevedo** [comment]
Use branch 234 and the Cesium map.

When zoomed out, single point graphics are to be displayed as a blue dot (small circle). When zooming in in Cesium, the test is a success if the blue dot does not change to a blue pixel.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
