### ISSUE TITLE
WMTS Service cannot be added to an Engine after Map Swap

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#245]
A WMTS service that is created in one engine, cannot be added to another engine once a map swap is performed.

**Comment by alberto-acevedo** [comment]
The reLoading of map in a map swap was ignoring wmts services. I added support  in the storage class to reload WMTS.

Test case :

Use branch 240:

Open a cesium map. 
Add a wmts service.
map sawp to WW or Leaflet. 
The test is a success if the wmts service renders on the map.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
