### ISSUE TITLE
WorldWind is blocking WMTS Services from displaying correctly

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#246]
WMTS (USGSShadedReliefOnly) is not being displayed correctly in WorldWind.

**Comment by jamesbeecroft** [comment]
![ww_wmts_display](https://cloud.githubusercontent.com/assets/25467634/25019017/1cb8ae6c-2057-11e7-99e8-14fe5a31ad0e.png)
![ww_wmts_errormessage](https://cloud.githubusercontent.com/assets/25467634/25019019/1cbc4054-2057-11e7-83a3-d1ddeb8fe31c.png)
![cesium_wmts](https://cloud.githubusercontent.com/assets/25467634/25019020/1cbea4ac-2057-11e7-9f1c-8847d1ccc5fb.png)

**Comment by jaybarra** [comment]
Being tracked on NASAWorldWind/WebWorldWind#113

**Comment by alberto-acevedo** [comment]
Worldwind is merging imagery layers. The solution is to render wmts with opacity set to 1.0 to avoid the look of merging of layers. I need to check if the opacity is exposed in the API  for worldwind..

**Comment by alberto-acevedo** [comment]
I was not able to replicate the strict transport security error in Chrome. I'm setting the use proxy but the proxy is not used by the engine.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 2.6.0 

Use API tester.

Render default WMTS as it appears in the API tester under General. The test is a success if the WMTS layers render on the map. See Cesiun snapshot above for comparison.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by mubinakhan** [comment]
Reintegrate
