### ISSUE TITLE
Worldwind reports no bounds if the map is not moved

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#254]
Start up the map, but do not move the map at all.
Go to Map.getBounds()
Retrieve the bounds.  It returns {}.

Same example will run correctly in Cesium.  The map needs an initial bounds from the engine.  The map instance stores the bounds for reporting.

This breaks drawing for MIL-STD autoshapes.

**Comment by jaybarra** [comment]
Test in development branch

To test,
* open WorldWind and do not move the map
* perform getBounds, it should be roughly correct
