### ISSUE TITLE
WorldWind sends duplicate mouseup and mousedown events to the core

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#259]
PointerEvents and MouseEvents are being sent to the core twice.

**Comment by jaybarra** [comment]
branch _bugfix/emp3-web#259-ww-duplicate-events_
To test use draw feature and edit feature tests. 
Both should behave as expected in regards to drawing and editing features.
Check console for errors; there should be none except for missing texture warnings.

**Comment by jamesbeecroft** [comment]
Reintegrate
