### ISSUE TITLE
The Map.drawFreehand onFreehandEvent parameter does not work

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#26]
Call Map.drawFreehand with the onFreehandEvent parameter. You can use this script below. In this script the callback should be called, but looking at the code we ignore the parameter.

var overlay = new emp3.api.Overlay(
{ geoId: "bob" }

);

var freebird = function(args)
{ console.log(JSON.stringify(args, null, 4)); }

;

map0.addOverlay({
overlay: overlay,
onSuccess: function() {
map0.drawFreehand(
{ onFreehandEvent: freebird }

);
}
});

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 45.
Use above script..
Open your  console log.
use the mouse and  freehand draw on the map. The test is a success if the console shows the freehand events from the map.

**Comment by mubinakhan** [comment]
[Uploading issue#26.PNG...]

**Comment by mubinakhan** [comment]
please verify

**Comment by mubinakhan** [comment]
![issue#26.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46e187893687c0fbd9abf301b44fff9e2c4533317346f67373dcb52aeb402d540c5e4aab41585711a8fcdf2aa7b42e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4e84b6bf8d44c8ed3525f5c6.PNG)

**Comment by alberto-acevedo** [comment]
The stroke width not changing in the event sent from the map is another issue.  Add this issue to GitHub.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the development  branch. Closing this issue.
