### ISSUE TITLE
Map.draw callback should reference the feature that was used as the input

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#262]
It would be more intuitive and less inconvenient if the feature that was returned in the callback args for Map.draw was a reference to the original feature used to initiate the draw.

The following script illustrates the issue
```javascript
var myFeature = new emp3.api.MilStdFeature(...)

map.drawFeature({
  feature: myFeature,
  onDrawComplete: function(args) {
    // args.feature is not a reference to myFeature but is a copy instead
    // The copy will likely have different position properties due to the drawing
  }
});
```

**Comment by alberto-acevedo** [comment]
Test case:

Use branch  301.

use Cesium

Use following script:

toastr.info(map0.geoId);

var overlay1 = new emp3.api.Overlay({
  name: "overlay1",
  id: "w834mne-sdg5467-sdf-we45"
});

var path = new emp3.api.Path({
  name: "myPath1"
});

path.track = "mubina";
// This is the event handler for mouse events.  We are looking for the double-clicking
// event.  If that occurs, complete the draw.
var completeDraw = function(args) {
  if (args.event === emp3.api.enums.UserInteractionEventEnum.DOUBLE_CLICKED) {
    map0.completeDraw();
   
  }
};

// Set up an event listener for double-clicking using the MAP_INTERACTION event.
// MAP_INTERACTION events occur for all user interactions with the map.  Inside
// the event we will filter out double-click events.
map0.addEventListener({
  eventType: emp3.api.enums.EventType.MAP_INTERACTION,
  callback: completeDraw
});

// After we know an overlay has been added, we can draw the symbol.
// You don't need an overlay to draw, but when the draw is complete,
// we want to add the returned feature to the map.
var processAdd = function() {
  var count = 0;

  alert("Click on the map to begin drawing; double-click to end.");

  // This just puts the map in draw mode, so the map begins
  // animating the draw.  It does not actually add data to the map.
  map0.drawFeature({
    feature: path,
    onDrawComplete: function(args) {
      // this is what actually adds the feature to the map.
       alert (args.feature.track);
      overlay1.addFeature({
        feature: args.feature
      });
    }
  });
};

var processError = function(error) {
  //alert(JSON.stringify(error));
};

// add an overlay to the map.
map0.addOverlay({
  overlay: overlay1,
  onSuccess: processAdd,
  onError: processError
});
Start drawing a line. double click on the map to complte thedarw. The test is a success if a pop up windoiw with the name Mubina is shown. The name Mubina was added as a property to te original feature. If the returned feature from the API has the same property that is proof that the same instance was returned to the client and not a clone or copy.

**Comment by mubinakhan** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2829d3e17cbd142e025e5b49ac41500a10f9af882aa4a42062c80d55b98e30063e937f03a6aa8019b500be2982488cb3b88e45c8ed3f37aa.PNG)

**Comment by mubinakhan** [comment]
reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
