### ISSUE TITLE
Ellipse editor can behave unpredicatable

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#273]
Create an ellipse at 40,40 semimajor 50000, semiminor 30000.

Rotate the ellipse 45 degrees.  Make semimajor smaller than semi minor.   Rotate.   On the first rotate the ellipse flips.   Editing after that gets weird, semimajor swaps with azimuth point and flips on opposite side.

**Comment by alberto-acevedo** [comment]
Fixed by not letting semiMajor to get smaller than semiMinor, and by not letting semiMinor to get bigger than semiMajor. By doing this there is no need to flip location of azimuth control point when locating it at the opposite site of the semiMajor (longest radius).

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
