### ISSUE TITLE
Double-click Feature interaction event does not occur in Cesium

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#279]
Double-clicking on a feature in Cesium does not produce the double-click interaction event.  Instead it zoom to the feature.  We should probably remove the zoom to behavior if it is not part of Cesium's behavior.  Investigate why this is happening and produce the double click event.

**Comment by alberto-acevedo** [comment]
Removed default listener that was set by the sdk. The default was tracking the feature double clicked.
  EmpCesium set its own listener for double clicking.

**Comment by alberto-acevedo** [comment]
Test case

Use release 2.5 branch.

Open Cesium. Add any  mil standard multipoint. Double click on it. The test is a success if there is no zooming to clicked feature.
