### ISSUE TITLE
setBackgroundBrightness is not working in WorldWind

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#280]
tracked in NASAWorldWind/WebWorldWind#112

**Comment by alberto-acevedo** [comment]
Notification from WW developers that a fix was integrated to the WW dev branch. I need to do a new buld of the WW sdk based on the dev branch.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 280.
Use WW

Open the api tester and set the map background brightness  in WW. The test is a success if the map turns white or black based on the values entered. (50 - neutral, 0 - black, 100 - white).

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
