### ISSUE TITLE
Symbols starting with `W` should ignore affiliation and status

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#282]
the validation tool should not give status or affiliation codes to symbols that begin with W

**Comment by alberto-acevedo** [comment]
Symbols starting with W  are of the coding scheme type METOC. For this kind of scheme the affiliation and status does  not  change.

**Comment by alberto-acevedo** [comment]
Conformed that the API tester is modifying the affiliation and status of METOC symbols. The renderer is returning back a single point canvas that is empty (L shape outline).

**Comment by alberto-acevedo** [comment]
Test case:

Use branch bugfix /282
Use Cesium and WW.

Plot single points mil stanadr of type scheme METOC . The test is a success if the siymbol renders on the map. (no empty cancas).

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
