### ISSUE TITLE
Line Weight affects Drawing Freehand Line in WorldWind

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#289]
When using drawing freehand in WorldWind, using a thick line weight (5) causes the drawn line to change as the user draws it.

**Comment by jamesbeecroft** [comment]
![ww_drawfreehand_linechangedraw](https://cloud.githubusercontent.com/assets/25467634/25436472/59ae25b8-2a61-11e7-96de-551723c54fb9.png)

**Comment by mubinakhan** [comment]
line width in cesium is different than in WW ( WW shows ways bigger than in cesium)

**Comment by alberto-acevedo** [comment]
Fixed by adjusting the outline width to be the same as in Cesium., and by bypassing the throttling when in No_PAN mode. NO_PAN mode is used by the greehand draw.

**Comment by alberto-acevedo** [comment]
Mubina -  Test this issue by using the dev branch.

**Comment by mubinakhan** [comment]
Reintegrate.
Stroke width should have limitations no more than 15.

**Comment by alberto-acevedo** [comment]
Already merged into the dev branch. closing this issue.
