### ISSUE TITLE
Line Color not applying in Freehand Draw

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#290]
When drawing in Freehand draw, setting the line color (Hex) does not change the color of the line.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 290.

Use Ww and Cesium

draw freehand . Set a color in hex (FFFF0036), width = 3. The test is a success if the line changes color, and width. Change the color and width, and test again.

**Comment by mubinakhan** [comment]
color changes and to go back to original color one have to "exit freehand draw" and commit it.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. c;losing this issue.
