### ISSUE TITLE
Set up DCGS-A Geospatial map server

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#296]
1. Download the latest DCGS-A Geospatial and map data and get working
2. Change samples in validation tool to use server.   
3. Instruct team what they need to do to get it working on each of our boxes.

**Comment by jaybarra** [comment]
For instructions please refer to the Confluence page

**Comment by alberto-acevedo** [comment]
Deployed server in my computer, deployed the imagery and terrain data. WMTS Imagery data does not works, WCS terrain data works. Waiting for new drops of server to test again.

**Comment by alberto-acevedo** [comment]
To locate the server in Confluence do a search for developer setup.

**Comment by alberto-acevedo** [comment]
Downloaded latest server as of Friday (5/12/2017)  WMTS not working yet. WMS and WCS works fine.

**Comment by alberto-acevedo** [comment]
The task of setting up of the server is complete. There are still issues with WMTS.  I will periodically get the latest version of the server from Nexus.
