### ISSUE TITLE
Implement Text Editor

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#297]
Allow WW users to draw and edit text primitives.

**Comment by alberto-acevedo** [comment]
EDitor ready for testing. The editor allows for the drawing of new text and editing of existing text. The ditor just drag the location of the text. The content of the text is the name assigned to the feature.

Test case:

Use branch #327 (Test in m y my computer until the network is back). 
draw a new text feature. Then edit the same text feature. The test is a success if the editor allows for the creation and then editing of text (dragging).

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
