### ISSUE TITLE
Map.setIconSize does not work in Leaflet

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#299]
in the map validation tool, set run the Map.setIconSize tool with some MIL-STD-2525 units on the map.    The size of the units is unaffected by leaflet.

The default size passed in from the configuration should also be the default size of the icons.

**Comment by alberto-acevedo** [comment]
The engine was still using the old V2 API call to set the mil std icon size. Changed it to call the config API function. Added pixel integer sizes corresponding to each string type size in the utils folder. 

Test case:

Use branch 240.

Plot some mil std icon on the Leaflet map.

Set the icon sizes. The test is a success if the icon change to a size corresponding to the size specified.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
