### ISSUE TITLE
Map.setMilStdLabels does not work

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#300]
Add a unit with all labels.  Navigate the leaflet map so you are below the mid distance threshold (in current version of map threshold is broken, so you may have to make a big difference between far and mid --try 60000000 and 3000000).  Turn on all labels using the Map.setMilStdLabels test, then set to use on the required labels.   The labels do not turn off.

**Comment by alberto-acevedo** [comment]
Test case:

Use Leaflet

set mid  range to 300000
set far range to 600000

plot a mil std icon with  many modifiers

Use the Map.setMilStdLabels . The test is a success if the labels show or hide with respect to the selected label mode.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
