### ISSUE TITLE
Nonsense if statement.

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-web#304]
There is an if statement in emp3.api.Map.js line 281 (if (args.backgroundBrightness !== undefined) {) performs the same operation in the then and else sections.

**Comment by alberto-acevedo** [comment]
Fixed by settind to a default brightness of 50 (no brightness) when the backgroundBrightness  is undefined.

**Comment by alberto-acevedo** [comment]
Test case:

Set map brightness. The test is a success if the  brightness works as expect.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
