### ISSUE TITLE
WW getLatLonFromXY process one XY

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-web#306]
WW function getLatLonFromXY only process one set of coordinate in item[0]. Leaflet and Cesium process all in a loop.

**Comment by alberto-acevedo** [comment]
Implemented in branch #306. A test passing in issue 307 also means this issue passes too.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
