### ISSUE TITLE
WW getXYFromLatLon not supported

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-web#307]
WW map engine does not implement getXYFromLatLon. It is required for the map grid lines.

**Comment by alberto-acevedo** [comment]
How To:  get the elevation from lat lon, you can use: 
var elevation = wwd.globe.elevationAtLocation(lat, lon)

To convert from screen coordinates to lat lon, you first need to go from screen coordinates to cartesian/model coordinates (x, y, z), and then to lat lon. To go from screen to cartesian coordinates and vice versa, use the wwd.drawContext.navigatorState.unProject and wwd.drawContext.navigatorState.project functions. The cartesian coordinates can be converted to geographic lat lon using the wwd.globe.computePositionFromPoint and wwd.globe.computePointFromPosition.

Checkout the documentation here for more information:
https://worldwind.arc.nasa.gov/asset...doc/index.html

**Comment by alberto-acevedo** [comment]
Test case:

Use branch #306.  
Use Worldwind
Use API tester.

Go to Map/conversion folder
Go to GeoToScreen. type 45,45 and execute. The screen coordinates should be near 1126, 506.
Go to ScreenToGeo. With mouse look for point on map that shows the screen values you got in previous step. Click mith mouse to select point and then  execute. The Geo coordinates should be near 45, 45.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
