### ISSUE TITLE
Counter Attack - yellow control point drags away on the map when editing 

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-web#313]
For reference use following script

**Comment by mubinakhan** [comment]
var counterattack = new emp3.api.MilStdSymbol({
  symbolCode: "GFTPKF--------X",
  positions: [
    {latitude: 20, longitude: 50}, // Tip of the arrow
    {latitude: 20, longitude: 49}, // Back of the arrow
    {latitude: 20.1, longitude: 49.8} // Shape of the arrow
  ]
});
this.props.addFeature(counterattack);

var overlay = new emp3.api.Overlay();
this.props.addOverlay(overlay);

map0.addOverlay({
  overlay: overlay,
  onSuccess: function() {
    overlay.addFeature({
      feature: counterattack,
      onSuccess: function() {
        map0.zoomTo({
          overlay: overlay
        });
        map0.editFeature({
          feature: counterattack
        });
      }
    });
  }
});

**Comment by alberto-acevedo** [comment]
Fixed already merged into the dev branch. closing this issue.
