### ISSUE TITLE
Leaflet cannot zoom out to world view

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#318]
Using 2 emp maps--one as a overview which shows the bounds of the second map.  The overview map is using leaflet.

On the overview map I want to show the entire map -180 to 180.   I cannot do that.  Inside leaflet-map-engine.debug.js a "fix" was added in to prevent the MIL-STD renderer from messing up if the bounds exceeded 180 degrees.  However the fix prevents me from seeing the entire world.  In my particular case I could not zoom out above 1000000 meters, which is not very good.

The method that causes this is checkMapWidth() which checks to see if the new zoom width of map is above 180 and then snaps back to the previous zoom level.   This ends up being jarring and frustrating.

Need to be able to see my entire map--Leaflet should not be restricted to zooming only to a quarter of the world.

**Comment by michael-spinelli** [comment]
so, unlock the zoom and we'll just have to make sure the bounds going into the renderer for the symbol is still limited.

**Comment by alberto-acevedo** [comment]
Fixed done in branch #240. The fix is exactly as MIke suggested. I'm not able to push the changes. The network is down again.

**Comment by mubinakhan** [comment]
reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
