### ISSUE TITLE
Cannot run Cesium and Leaflet side by side

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#319]
When Cesium is loaded, you cannot run Leaflet in emp.  

To duplicate Open Leaflet map.   Then open Cesium map.   Leaflet appears to load fine.   Make sure to open leaflet first, then cesium.   Cesium overwrites the leaflet library variables.   The viewerCesiumNavigationMixin is what is overriding Leaflet. The leaflet EMP uses is 1.0.3, the navigation mix in uses Leaflet 0.7.7.  This overwrites Leaflet's variables, and screws up anything to do with adding features.   This is an extemely important issue to me as when Leaflet and Cesium are running side by side, Leaflet cannot load data.

**Comment by alberto-acevedo** [comment]
The dependency on Leaflet is not need it inside the Cesium navigation plugin. I'm removing the dependency from t he plugin.

**Comment by alberto-acevedo** [comment]
Test case:

Open leaflet, and then Cesium so the 2 maps are open simultaneously. Plot a polygon in Leaflet. The test  is a  success if the [polygon renders on the leaflet map.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
merged into the dev branch. closing this issue.
