### ISSUE TITLE
Leaflet will not display a Path with a stroke color

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#320]
Go to tester.  
create a new path with stroke color set to 255,255,0,1 (solid yellow).
Add to map.

The line will not draw.   The problem is the stroke width is being set to NaN in leafLet.utils.geoJson.mergeGeoJSONProperties.   This occurs during the construction of the Leaflet object in 
leafLet.internalPrivateClass.GeoJsonFeature._createFeature.  This will occur if strokeWidth is not set and the color is set.

**Comment by alberto-acevedo** [comment]
Fixed by adding a default line width = 3 inside the mergeGeoJSONProperties function.

**Comment by alberto-acevedo** [comment]
test case:

Use branch 240:

Use Leaflet

Plot a path with a stroke color and no stroke width,. The test is a success if the path renders on the map.

**Comment by mubinakhan** [comment]
![320.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46bbc6ca61cec1b99de6b546a749b2ce6b137f707052a17f72d3b62bee162c515f571bf8440e5e45feeb9539e4e76224d50152a7842f4d7ed43f17a6b98616b706bf238a4d80bfb4825e8d.png)

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
