### ISSUE TITLE
Animation line is not animating when edting in Cesium

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#321]

**Comment by alberto-acevedo** [comment]
The callback property used o speed up the updating of the poly lines coordinates was incorrectly using a global variable that was shared among all edited poly lines.  The fix is to replace the global variable with a function that takes the positions as an argument and then returns that same positions (wrapper function) . The wrapper function is called using bind inside the callBackProperty.

**Comment by mubinakhan** [comment]
Reinetgrate

**Comment by alberto-acevedo** [comment]
Fixed in branch #298. I'm not able to merged into the dev branch because my computer is in quarantine since last Thursday.

**Comment by alberto-acevedo** [comment]
merged into the dev branch. closing this issue.
