### ISSUE TITLE
Developer guide quickStart page stopped working

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#325]
Developer guide QuickStart page stopped working after the last sprint release.

**Comment by alberto-acevedo** [comment]
test case:

Open the dev guide's quickStart page. The test is a success if the map shows.

**Comment by mubinakhan** [comment]
Map shows.Reintegrate

**Comment by alberto-acevedo** [comment]
Already merged into the dev branch. closing this issue.
