### ISSUE TITLE
Infiltration lines In WW and Cesium don't plot the control points in edit mode properly

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-web#329]
Go to Tactical graphics/ Command and control/Offense/lines/infiltration lines/

**Comment by alberto-acevedo** [comment]
The control point for width has the same color as the control points used for settting the length. The fix is to change the control point type as width. Changing the type changes the color.

**Comment by alberto-acevedo** [comment]
Test case:

Use Cesium or WW.
Plot an infiltration line. edit the line. The test is a success if the width control point is gray differentiating it from the other 2 blue control points.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
merged into the dev branch. Closing this issue.
