### ISSUE TITLE
WMTS does not work

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#331]
WMTS does not allow you to select the important TileMatrixSet parameter and important part of the specification.  This is from the API, to the core, down to Cesium.  In the Cesium engine, the TileMatrixSet is always set to 'default28mm' which works for the sample service in the API tester, but not some other WMTS services.  There are many other services that use tileMatrixSets with different names.   The getCapabilities for the WMTS service sends back the available tileMatrixSets and in the layer metadata it displays which tileMatrixSets are available for that layer.

Propose 'tileMatrixSet' property onto WMTS class.   Without it, WMTS doesn't make much sense.
Propose removing the default28mm default tileMatrixSet from Cesium.

**Comment by sjpinizzotto** [comment]
Furthermore, the layer parameter in leaflet will never be set because of this code in EmpCesium.js

if (this.isV2Core && item.activeLayers) {
        sLayers = item.activeLayers.join();
      } else if (!this.isV2Core && item.layers) {
        sLayers = item.layers.join();
      }

WMTS does not have any activeLayers, therefore sLayers will always be empty.  WMTS can only display one layer at a time.   The proper transaction item will have .layer property which should be used for the request.

**Comment by alberto-acevedo** [comment]
Added the 'tileMatrixSet' to the WMTS class, and to related classes in the API and core. Modified in EMPCesium to expect a single WMTS layer name.

I tested in Cesium and the tileMatrixSet is passed to the engine.

I'm not able to do a push into the dev branch because I have no internet connection. (bad switch)

**Comment by alberto-acevedo** [comment]
I also added the property to the validation API..

**Comment by alberto-acevedo** [comment]
test using branch 240.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
