### ISSUE TITLE
Change surface polylines to use rhumb as path type instead of the default great circle (geodesic).

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#332]
Control points are not aligning to lines (surface polylines)  because the default path type in WW is great circle. The use of path type as rhumb fixes the issue. 

Related to this issue, the SEC renderer generate canvas multipoints that uses rhumb. path type. In Cesium there is no option to change the path type. The path type is Cesium is great circle, but this has been flagged as an issue because there must be the option to change the path type to rhrumb.

All 3D engines must  use the same path type to keep the consistency.

**Comment by alberto-acevedo** [comment]
Test case:

Plot an Infiltration line. Edit the line. The test is a success if the width control point (gray) aligns with the line.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
