### ISSUE TITLE
Cannot remove a map service if more than one map has been created.

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#334]
Create two maps.  Add a map service to each map.  Try to remove the services from both maps.  You cannot in API because getMapServices reports no layers on one of the maps.  But even if you had the map service you would not be able to remove it.   

Internally the core is sending back the default overlay where the services should be added.   However in the v2 to v3 upgrade it looks like it was never accounted for that multiple maps would be returning their overlays.  The default overlay gets overwritten, and the api can never send the correct overlay for one of the maps, as it has been overwritten.  

Ideally each map should know the overlay for the wms services so that this issue does not occur.

**Comment by alberto-acevedo** [comment]
Fixed as suggested by Steve.

Test case:

Use branch 240

Open the Cesium map Add a  WMS service.
Open the Leaflet map Add a  WMS service.
Remove the services from both maps. The test is a success  if all services are removed from the both engines.

**Comment by mubinakhan** [comment]
Reinetrgate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
