### ISSUE TITLE
New Map can't accept the same Geo Id and name when adding WMTS layer.,

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-web#338]
*Go to API tester
*Select any map 
*Create WMTS layer 
*Add values and create WMTS 
*Now add another map 
*Select a different map( if cesium was selected earlier now select world wind)
*Select Map 1 / create WMTS layer 
*layer will not be added unless Geo ID , Name and description is changed also 
* for reference ( issue 321)

**Comment by mubinakhan** [comment]
![retain doc](https://user-images.githubusercontent.com/25485443/27749532-ef62cbfe-5da1-11e7-9dc9-d3f7586d3513.png)

**Comment by mubinakhan** [comment]
![retain](https://user-images.githubusercontent.com/25485443/27749539-f66c9f7e-5da1-11e7-8565-8f47c1453461.png)

**Comment by alberto-acevedo** [comment]
-In  EmpWMTS class  it was missing the update class. The options was incomplete.
-  Allow now the reuse of same WMTS stored object for different engines. Before only WMS was allowed to reuse the stored WMS. 
- fixed issue in intent that was incorrectly accessing the editor manager  status  function when doing  feaature updates.

**Comment by alberto-acevedo** [comment]
Test case:

Use dev branch.
Open Cesium.
Plot WMTS. Stay in this WMTS test.
Open second map: WW. Plot same WMTS as in Cesium. Use map1. The test is a success if the WMTS tiles render on WW.

**Comment by mubinakhan** [comment]
![Capture1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46cb958a379791acdeabf301b44fff9e2c4533317346f67373dcb52aeb402d540c5e4aab41585711a8fcdf2aa7b42e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4f8cb4bf8949c8ec3a26f5c6.PNG)

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Already merged into the dev branch.  Closing this issue.
