### ISSUE TITLE
Cannot change the name of a feature to an empty string

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#343]
Create a feature with a name on the test program.  Change the name to an empty string.   Update or re-add the feature.  (must make sure you use the same geoId).   The feature does not update.

This occurs on all map engines.

**Comment by alberto-acevedo** [comment]
Issue was in the API and core. The API and core were ignoring empty strings for name. Fixed in branch #351

**Comment by alberto-acevedo** [comment]
Merged fix into the dev branch. closing this issue.
