### ISSUE TITLE
Implement Map.setMotionLockMode in Worldwind

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#35]
Worldwind will have to implement Map.setMotionLockMode for Point editing (#13) to work.

**Comment by jaybarra** [comment]
Branch: **feature/emp3-web-#35-ww-lock**

Affects WorldWind
### Features
* map.setMotionLockMode supports all lock modes now, not just locked and unlocked
* smartMotion will listen for a mousedown and move events only near the edges of the map
  * should be able to drag to the sides and to the corners for diagonal movement
  * motion should scale with altitude, higher altitude and lower altitude motion should not be too fast or slow (ie 500m elevation doesn't have you move to the next continent)
* preventing wheel events is not properly supported yet

**Comment by jamesbeecroft** [comment]
reintegrate
