### ISSUE TITLE
Implement Map.setMotionLockMode in Leaflet

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#36]
This will be need in order for (#13) to work.

**Comment by nclark25** [comment]
Testing Procedure:

All options under Map.setMotionLockMode() should now work in Leaflet. When testing the various options make sure that the following items listed below are accounted for:
- FeatureInteraction AND MapInteraction events are still firing when map is locked.
- MapViewChange events should still fire in any lock state where the map has the ability to move and movement has occurred.
- When the map is set to NO MOTION an error should be generated if a view change of ANY kind occurs from the API (Validator). This error should show in the console window.
- Any lock state with the exception of NO MOTION should respond to API (Validator) view change requests.
- When there are graphics on the screen and the map is set to -> SMART MOTION ensure that when panning the graphics that enter the viewing area update as necessary or at least don't change in an unexpected way.
- Make sure everything all options work after resizing the map window .
- Make sure the zoom button in the upper right corner disappears when any lock option that disables zoom is enabled. Also make sure the zoom button works whenever it is present on the screen.

**Comment by jamesbeecroft** [comment]
Reintegrate
