### ISSUE TITLE
Change Feature.removeFeature callback to remove featureIds parameter and replace it with features

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#39]
For consistency with the rest of the API we don't send back feature ids anymore.  We will replace it with features[] which will send back an array of the Features that were removed.

**Comment by erikamarie** [comment]
To test fix:
1) Create overlay
2) Create features f1, f2, f3, f4
3) Remove features by selecting f1 and f2 and "Delete selected features"
4) In top right corner of window hover over toaster popup. Identify f1_#######, f2_####### listed as successfully removed

To test test case:
1)Load test script
2) search for "handleUnplotFeatureTransactionComplete"
3) Verify two channels found and onSuccess was called
