### ISSUE TITLE
Single point features are not scaling when selected in Cesium

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#41]
According to the documentation, when a single point feature is selected it should scale 20%.    This is not happening.

**Comment by alberto-acevedo** [comment]
Fixed in branch  emp-map#43

**Comment by alberto-acevedo** [comment]
use test case in branch emp-map#43.

**Comment by jamesbeecroft** [comment]
awaiting fix to branch 43. selection size is not increasing.

**Comment by alberto-acevedo** [comment]
I was not able to replicate. Try again by completely removing the branch from you computer and pulling it again. There were multiple branches with the same name but different folder.


-----Original Message-----

**Comment by alberto-acevedo** [comment]
Fix already merged in the dev branch by merging issue #43. Closing this issue.
