### ISSUE TITLE
The map has odd behavior if Map.drawFreehand is called during a Map.editFeature

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#45]
Each map instance maintains a state: "ready", "edit", "draw" etc. Add a new state for "freehand".

When map enters into freehand mode, it is incompatible with the draw or edit mode. It should check prior to entering into that mode to see if it should cancel the draw or edit transaction.

Similarly if you are in edit or draw modes, and try to go into freehand mode, it should prompt if you should finish the draw or edit transaction, otherwise cancel out of the freehand draw.

**Comment by alberto-acevedo** [comment]
new state of freehand was already in the core. Now asking the user about continuing with new freehand operation while cancelling any current draw/edit operation, and vice versa.

Use branch #45

Plot a path. Edit path. while in edit mode go to freehand mode. The test is a success if  a confirmation is shown to the user asking about proceeding with the freehand mode and cancelling the edit operation.

Draw a path. While in draw mode go to freehand mode. The test is a success if  a confirmation is shown to the user asking about proceeding with the freehand mode and cancelling the draw operation.

Start freehand mode. While in freehand mode edit a feature. The test is a success if  a confirmation is shown to the user asking about proceeding with the edit mode and cancelling the freehand operation.

Start freehand mode. While in freehand mode draw a feature. The test is a success if  a confirmation is shown to the user asking about proceeding with the draw mode and cancelling the freehand operation.

**Comment by mubinakhan** [comment]
[Uploading issue#45.PNG...]

**Comment by mubinakhan** [comment]
verify

**Comment by mubinakhan** [comment]
![issue#45.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58daa047b12bc6001be7a9c1/125516c66e82c728ace21e0d46e187893687c0fddaabf301b44fff9e2c4533317346f67373dcb52aeb402d540c5e4aab41585711a8fcdf2aa7b42e6c981e5ab38532022d8c6853beb2901db90bbb258b4e84b6bf824dc7ee3f2df5c6.PNG)

**Comment by alberto-acevedo** [comment]
Working as expected, I don't see anything wrong in the snapshot.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the development  branch. Closing this issue.
