### ISSUE TITLE
emp3.api.Point class ignores iconUrl property

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#47]
Cannot specify an icon to display other than the default icon for Cesium.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch bug/emp3-map#47.

Don't forget to set the proxy URL in the config file to reflect your server location.

Plot a point with the following iconUrl: http://www.hwb.com/gruhn/programming/python/star-small.png
The api tester has no option to set the proxy for the case of point. Cesium defaults to use the proxy when the client doesn't specify the use of proxy. The test is a success if a star renders on the map.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged to the branch 55 that was already merged into the dev branch. closing this issue.
