### ISSUE TITLE
Cesium is not rendering dataURL points.

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/emp3-web#55]
Cesium is rendering the emp default icon when there is an iconUrl that represents a dataUrl.

**Comment by alberto-acevedo** [comment]
Test case:

use branch 55

use following dataUrl image to set the iconUrl:

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAiCAYAAAA3WXuFAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAASdEVYdFNvZnR3YXJlAEdyZWVuc2hvdF5VCAUAAARMSURBVFhHzZZbUI1RFMe3YYzbmMkYGWIYjMu4T8ZlyCWaSiLVERVlzlRSdJHmpHKii1BDhUrjuCRyq6SEdFMxnrx4MR68ePDIePJgOf9t9p7v69unOt14+M053/7W2uv/rbX32pt1dL8n0N71nlo731FLx1tOc3s3Nbd10avWTnrR8oaeN7dT48s2qm9qobrGZnry7AU9etpE1TUNVPWoniof1NHNe4/JVvWYKu48oPJb9+najSoqqaikovLbdKnURgUlFXSh+DrlXy6j3MJrlFNwlc5eKKGs80VkzS+izLxLxF61ddKmTRv/KZas85RqPUcpmXnEGl+2KI1GkhPp2ZR86gwlWrKI1dpTrzIaSRIsVjp2MpPiUzKIPax5pjQaSeJS0ik2KY1iEi3Eqh7WKo1GkoiYRAmzVVYrjUBA0lIy33KjXVErlO+HioPRxyWszHZXaQQR+b8Z59yvUeQd4q60GwpCzcckrNjeH1RGh67MlYLAPutCirrrRtnfx9CJdy60xWu90m8ghEQelbCC4nIy22bJQJ5+67jRjoA1fAxisr6N5eXTCowsnUObt2+gIMti8jOvNARxBlNErITlXizWBYI4Hih1CQdCkA3fyFU6O2Qw9cNk/h8lPZC7QBmsPwSGR0mYNa9QF+hwxWyeKfEcVjhPOiIrGV/GU3zTNJ5BrR98sM4S26dQwuupTq25gFCzhFnsLRtBEQgToWTaQMiCahKQ/nmCtEPGLB8nGfwwX1/i/EMiJSw57Qz/Ou06EKUAyJjWWQuChV2cz0uL59Nfx0k/fCDKjXLiObZ2usFf4GeKkDC0azhgMrxEEIhDIFPGIoNzb8A+5+doDha7tvQAa1Pl5xt4UMJiEizcGJOg9+AXz8ldLkrnvtAGjb4/U4oRH6zCe2+YhB2OTeZpDc1fQHH1rnICMNhmCHHYCHENrr3O5bXngIQFh0eTx9a/X6VthsjUUDa/3tixe7+EbfffrzurIAqZGmyzcwZoEDDPXSG8qcVUz+ClS/s00f5irdJxuIAGAdvmt4/2xC/TrR2cWSrH4QIaBGzrThN5BbvrBGEhqhyHC2gQcEEYxC5Dp8WOcNQvhgudoC2+wbznoDv7H1mudHAEmigOXdU7Z4AGAdvsEyRLhWuGykGFOBYAzkCVTX+BBoFOUM6P0UoHFTjxhSCAncmbq73kEKvycYRBEDKDy5gzdxosfHwExMAXN0qtQNGZ+7MeDYKcPUQFOIBxXiE4BGoF4QaAUuI/NgvWm2oOYBCELxXdeqA7DKKQaQhAc4UgrUCIV/kBpSCUSxyuuMs4063FvQiZ9glfzcdw9EAI5gMoaU8/gU6Qh08gF6Dq1j0vYI7oeXMU4/DFnaivzg8NAi4Ip33PO7K4xIuUO+reEK3NhLh9Yt2A/hzSBkHiBVIOEVioCIQAQhDG0QTxi0DIqPDDmLDF1hcZwzPWk7BzhEHQ/0Mg/QEjhC3PHfK5AgAAAABJRU5ErkJggg==

The test is a success if a G green icon renders on  the map.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
