### ISSUE TITLE
Add KML layer support to WorldWind

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#6]

**Comment by jaybarra** [comment]
## Test Branch
_feature/emp3-web#6-ww-kml-layer_

## Test Instructions
1. Unzip the KML_samples.kml file and place it in the top of the emp3-validation
2. Verify if you navigate to http://localhost:8080/emp3-validation/KML_samples.kml the file resolves
3. Create a WorldWind map
4. Run the following script
```javascript
var kmlLayer = new emp3.api.KMLLayer({
  name: 'test kmllayer',
  url: 'http://localhost:8080/emp3-validation/KML_samples.kml'
});

this.props.addMapService(kmlLayer);

map0.addMapService({
  mapService: kmlLayer,
  onSuccess: function() {
    map0.setCamera({
      camera: new emp3.api.Camera({latitude: 35, longitude: -125, altitude: 5e6})
    })
  }
});
```
5. Verify points show up on the map
6. Remove the KML Layer via RemoveMapServiceTest
7. Verify KML disappears

Test with other KML links as necessary

**Comment by jamesbeecroft** [comment]
Reintegrate
