### ISSUE TITLE
Move WorldWind renderer calls to a webworker

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#61]
As a performance measure calls to the renderer could be moved out of the editor controller and into a webworker.

**Comment by alberto-acevedo** [comment]
Test case:

All rendering of multipoints is done by calling a worker.

Plot a mil standard multipoint. The test is a success if the graphic renders on the map and it keeps rendering when zoming in and out.

**Comment by alberto-acevedo** [comment]
The worker can handle batch calls but that requires converting most of the functions to start accepting batch calls. Right now worldwind is calling the worker for each feature plot and update. Not using batch calls is a performance hit. Using batch calls should  be done in a separate branch.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
