### ISSUE TITLE
Implement getBounds for WorldWind

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#62]
getBounds returns undefined currently for WorldWind

**Comment by jaybarra** [comment]
test branch: *feature/emp3-web#62-ww-getBounds*

WorldWind getBounds commands should return sensible values for the bounds and should correspond roughly with the coordinates the mouse gives when you inspect the boundaries of the visible map.

**Comment by jamesbeecroft** [comment]
Reintegrate
