### ISSUE TITLE
WorldWind needs to re-render multi-point symbols when zooming

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#64]
WorldWind is not currently re-rendering when changing the zoom levels correctly resulting in geographicText objects not sitting in the correct location relative to the parent shape.

**Comment by jaybarra** [comment]
Testing Branch: **feature/emp3-web#64-ww-rerender**
This fix affects the WorldWind engine only
Fixes: 
* Multi-point MilStd features should re-render correctly when moving the camera and when changing altitude

**Comment by jamesbeecroft** [comment]
Reintegrate
