### ISSUE TITLE
Reduce the output that goes into the Cesium dist folder during a build

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#68]
Remove anything unnecessary (test dir for example) and shrink the size of the build outputs

**Comment by alberto-acevedo** [comment]
-- Removed the test folder from the distribution. Removed from the dist folder the IAU2006_XYS, maki, and NaturalEarthII folders that were inside the sdk. Size was reduced by 2.4 MB.

Merged changes to the dev branch. Closing this issue.
