### ISSUE TITLE
Update validation tool to be able to use the proxy settings

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#7]
The validation tool is currently not capable of using the proxy settings (the node server is not currently interpreting the jsp file and is serving it raw)

**Comment by jaybarra** [comment]
Workaround is to host required resources locally.

**Comment by alberto-acevedo** [comment]
The issue is when using webpack. The workaround is to enable CORS  in the servers hosting the services, or as Jay stated above , host required resources in same server as EMP map so use of proxy is not needed.

**Comment by alberto-acevedo** [comment]
This is a webPack limitation when dealing with proxies of type jsp (Java). Closing this issue.
