### ISSUE TITLE
Implement polygon editor for primitives

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#82]

**Comment by sjpinizzotto** [comment]
Jimmy, test all editing polygon graphics making sure to test both Polygon primitives and Polygon MIL-STD-2525 symbols such as FFA, Assembly Area etc.  Primitives and Polygons use different threads of code so verify for both the edit events are being raised through the addEventListener (FeatureEditEvent), and that the callbacks are being raised (the toasters that pop up during editing).  Verify the updates show all the coordinates, verify the callbacks all have the correct parameters according to our documentation.

**Comment by jamesbeecroft** [comment]
Reintegrate. All polygons (Primitive and Mil-Std) had no issues editing and all listener messages fired correctly (Start, Update, Cancel, and Complete)
