### ISSUE TITLE
In Worldwind, Point.iconURI primitive should support base64 images 

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#84]
This is to make line editors work.  The vertices will be base 64 images.

**Comment by jaybarra** [comment]
## Test values
* url -  https://upload.wikimedia.org/wikipedia/commons/e/e0/Globcal_medium_resolution_globe.png
* base64 data  (16x16 red square)
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAHklEQVQ4T2P8z8Dwn4ECwDhqAMNoGDCMhgHDsAgDAKXUH/HLXNS/AAAAAElFTkSuQmCC

**Comment by jamesbeecroft** [comment]
Reintegrate
