### ISSUE TITLE
In Leaflet, Point.iconURI should support base64 images.

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#85]
This is to make line editor work.

**Comment by nclark25** [comment]
Leaflet icons already support the use of base64 images. I will test simple graphic editing to make sure the images are showing up.

**Comment by nclark25** [comment]
Simple graphics and mil-std graphics seem to now display the proper editing handle graphics. Moving the points is not currently working, but I will write up an additional issue for this.

**Comment by nclark25** [comment]
Testing Procedure:

Just make sure the editing handles appear when editing various graphics. Editing will not work yet.

**Comment by nclark25** [comment]
Issue #193 contains this fix because it is required for editing. Therefore, this issue will be closed.
