### ISSUE TITLE
Map.setMilStdLabels is not working

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#88]
engineInterface.map.config is sending over just the messageId and no settings.

**Comment by erikamarie** [comment]
To test:
-activate the map set milstdlabels from the tester
-verify toaster popup states the labels have been changed to the selected label

-verify on the map engine that the labels have changed

**Comment by erikamarie** [comment]
Fixed in core and in cesium. To test try changing the labels on a satellite. Apparently this intentionally does not toggle labels for multipoint graphics

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by erikamarie** [comment]
Closed #88
