### ISSUE TITLE
WorldWind needs to keep track of selection status on its own features

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#94]
This affects several issues involving re-rendering
WorldWind needs to keep track of the selection status of its own features based on messages from the core.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch 94.

Plot single milstd single points. Select the feature. Zoom in and out . The test is a success if the feature keeps its selection state. when transitioning from dot to mil std symbol.

Repeat the same for mil std multipoints. Zoom in and out. The test is a success if the feature keeps its selection state.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
