### ISSUE TITLE
Deleting a point in edit mode will not remove symbol from map.

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#95]
Add a point,
Put point in edit mode,
Delete symbol
point stays on map.

It will also stay on map regardless if editing is complete.

**Comment by sjpinizzotto** [comment]
Discovered when cancelling or completing an edit, a link is established back to map root.  Once this occur and the link to the parent overlay is removed, there is no command being sent to the engine to remove.  Investigating what is causing this link.

**Comment by sjpinizzotto** [comment]
Method emp.editingManager.edit() is creating a emp.typeLibrary.Feature class through copying the object in the data store.  The method used is feature.getObjectData(mapInstance, parentCoreId).   The mapInstance is being passed in as the parentCoreId, and that is what creates that extra link later on.   The parentCoreId is currently required by Cesium as a V2 holdover, and was not available from the emp.storage.findFeature method, so we thought that getObjectData would fix this.  without the parentCoreId the cancel fails to restore to original state.  Looking at other methods for retreiving the correct parentCoreId and potentially removing the need for it in Cesium since it is no longer required in our v3 baseline.

**Comment by sjpinizzotto** [comment]
Jimmy, 
to test, add point or line.  edit feature.  test cancel, and delete line/point  it should remove.   do the same for complete and delete.   Items should delete.

then test polygons make sure they still work too.

**Comment by jamesbeecroft** [comment]
Reintegrate
