### ISSUE TITLE
Cesium is ignoring the useProxy value for points and defaulting to always using it

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#96]
In the validation tool I created a point with a URL to an icon, and saw the useProxy value was set to false. The browser threw a 404 that it was attempting to locate the feature at http://localhost:3000/urlproxy.jsp?...

**Comment by alberto-acevedo** [comment]
Test case,

Plot a point with a local or external icon URL. Do not set the useProxy. The test is a success if the proxy is not used. Open the debugger network tab to verify the URL that is used to render the point. The icon will default to the default emp icon if the icon url is external to the server hosting the map.

**Comment by alberto-acevedo** [comment]
Use branch #101

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. Closing this issue.
