### ISSUE TITLE
Fill patterns (hatched/cross-hatched) are not being applied to primitive shapes in Cesium

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#99]
When creating primitive shapes in Cesium (circle, ellipse, square, rectangle, polygon) only the solid fill pattern can be applied to the shapes. When selecting hatched or cross-hatched fill patterns, the fill is still solid.

**Comment by alberto-acevedo** [comment]
This is low priority. I need a way to set the fill of primitives (circle, ellipse, square, rectangle) with fill pattern hatched, cross hatched , and solid like you do with the renderer for the  hatched fill for the "no fire"  multipoint.

**Comment by mdeutch3** [comment]
@michael-spinelli Are they supposed to be passing fillStyle as a modifier? I don't see it in populateModifiers. I know we were using texturePaint. Did that replace fillStyle?

**Comment by michael-spinelli** [comment]
I don't think we take a fillStyle at the moment.  It's something we'd have to add.  For multipoint canvas and svg output it wouldn't be to hard.  I don't know how much of a pain it would be for you to add to kml & geoJSON.  @alberto-acevedo , were you only planning to use this for basic shapes or was it for any multipoint symbol?

**Comment by mdeutch3** [comment]
fillStyle is in the renderer. In Java version I'm set up to test render_GE without having to go through the interface. It renders fill styles 2-5, and 8, returns shapes suitable for conversion to KML, geoJSON: forward diagonal, backward diagonal, vertical, horizontal, and cross-hatch. I'll confirm with the JS tester.

**Comment by mdeutch3** [comment]
The above fill styles display in web version for KML and geoJSON. Not for svg which throws an error: fillColor.getAlpha is not a function. For KML and geoJSON we would need to clip for all symbols which have hatch fill, which we don't do currently, or it is going to crash if you zoom in because of all the hatch lines.

**Comment by mdeutch3** [comment]
This is a bug. We apparently are not displaying hatch fill for the Mil-Std-2525 symbols that have it: NFA, WFZ, Chem, Bio, when format is set to svg.

**Comment by mdeutch3** [comment]
Is pattern fill working with SVG for the METOCs? I see hatch fill working with the canvas format, e.g. NFA, but not for SVG. I don't see the METOC fills working with either SVG or canvas format.

**Comment by alberto-acevedo** [comment]
Is pattern fill now supported for svg in the latest renderer?

**Comment by mdeutch3** [comment]
The above bugs were fixed. It works for the symbols that require it, including METOCs, but not we still do not take a fill style parameter.

**Comment by mdeutch3** [comment]
@michael-spinelli MilStdSymbol currently uses a TexturePaint object for the fillStyle property. Add a fillPattern property?

**Comment by mdeutch3** [comment]
Source changes have been checked in. However populateModifiers is throwing an error if PATTERNFILLTYPE is not set by the client. And when it is set we are getting a boundary line around the outer shape for the parameterized (PBS) basic shapes for SVG format.

**Comment by michael-spinelli** [comment]
I fixed the patternFillType error and checked in the code but now I'm seeing:
clsUtilityCPOF Change1TacticalAreas
Severe: ReferenceError: EllipseGeometry is not defined - Failed inside Change1TacticalAreas

armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsUtilityCPOF.Change1TacticalAreas@file:///C:/Users/michael.spinelli/Documents/code/Github/missioncommand/mil-sym-js/web/js/src/armyc2/c2sd/JavaRendererServer/RenderMultipoints/clsUtilityCPOF.js:434:25

**Comment by michael-spinelli** [comment]
Ok, I never updated my tester to load your additional circle functions, let me try that.

**Comment by michael-spinelli** [comment]
@alberto-acevedo , In version 0.3.20, you will have MilStdAttributes.PatternFillType.  Type can be accessed from: armyc2.c2sd.renderer.utilities.FillPatterns like "FillPatterns.PatternCrossHatch".

FillPatterns.PatternSolid : 0,//does nothing.
    PatternCrossHatch : 8,//X
    PatternForwardHatch : 2,// /
    PatternBackwardHatch : 3,// \
    PatternVerticalHatch : 4,// |
    PatternHorizontalHatch : 5,// _

**Comment by alberto-acevedo** [comment]
Nice work with the patterns. Thanks.

**Comment by alberto-acevedo** [comment]
Test case:

Use branch feature/99.

Plot emp primitives and set the fill patterns. The test is a success if the pattern renders on the map.

**Comment by jamesbeecroft** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
